apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: micro
spec:
  replicas: 1
  selector: { matchLabels: { app: api } }
  template:
    metadata: { labels: { app: api } }
    spec:
      containers:
        - name: api
          image: DOCKERHUB_USER/api:IMAGE_TAG
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: micro
spec:
  type: ClusterIP
  selector: { app: api }
  ports:
    - port: 8080
      targetPort: 8080
